from __future__ import annotations

import base64
import time
from dataclasses import dataclass
from pathlib import Path

_PNG_1X1 = base64.b64decode(
    # 1x1 transparent PNG
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+X3b0AAAAASUVORK5CYII="
)


@dataclass
class DemoResult:
    text: str


class DemoQuickAgent:
    """Agent that produces logs and artifacts without any external credentials."""

    def __init__(self, *, workspace: str, **_kwargs):
        self.workspace = Path(workspace)

    def invoke(self, inputs):
        prompt = inputs if isinstance(inputs, str) else str(inputs)

        # Print logs to subprocess stdout so the dashboard can stream them.
        print("[demo_quick] starting")
        print(f"[demo_quick] prompt: {prompt}")

        art_dir = self.workspace / "artifacts"
        art_dir.mkdir(parents=True, exist_ok=True)

        txt_path = art_dir / "demo_output.txt"
        txt_path.write_text(
            "This is a demo artifact generated by DemoQuickAgent.\n"
            f"Prompt was: {prompt}\n",
            encoding="utf-8",
        )
        print(f"[demo_quick] wrote {txt_path.name}")

        img_path = art_dir / "pixel.png"
        img_path.write_bytes(_PNG_1X1)
        print(f"[demo_quick] wrote {img_path.name}")

        print("[demo_quick] done")
        return DemoResult(
            text=f"DemoQuickAgent finished. Artifacts: {txt_path.name}, {img_path.name}."
        )

    def format_result(self, result):
        if isinstance(result, DemoResult):
            return result.text
        return str(result)


class DemoSlowAgent:
    """Agent that runs long enough to test streaming and cancellation."""

    def __init__(
        self,
        *,
        workspace: str,
        steps: int = 60,
        sleep_s: float = 0.25,
        **_kwargs,
    ):
        self.workspace = Path(workspace)
        self.steps = int(steps)
        self.sleep_s = float(sleep_s)

    def invoke(self, inputs):
        prompt = inputs if isinstance(inputs, str) else str(inputs)
        print("[demo_slow] starting")
        print(f"[demo_slow] prompt: {prompt}")

        art_dir = self.workspace / "artifacts"
        art_dir.mkdir(parents=True, exist_ok=True)

        prog_path = art_dir / "progress.txt"
        for i in range(1, self.steps + 1):
            line = f"step {i}/{self.steps}\n"
            print("[demo_slow] " + line.strip())
            # Update an artifact incrementally so workspace panel can see it.
            prog_path.write_text(
                "".join([f"step {j}/{self.steps}\n" for j in range(1, i + 1)]),
                encoding="utf-8",
            )
            time.sleep(self.sleep_s)

        print("[demo_slow] done")
        return DemoResult(
            text=f"DemoSlowAgent finished after {self.steps} steps."
        )

    def format_result(self, result):
        if isinstance(result, DemoResult):
            return result.text
        return str(result)
